colorscheme desert
syntax on
set number
set expandtab
set smarttab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set cursorline
set cursorcolumn
set ttyfast
set showmode
set showcmd
set laststatus=2
set statusline=\ %F\ MODE=[%M]\ TYPE=%Y\ ROW=%l\ COLUMN=%v\ BUFFER=%n
set wrap
set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.xlsx,*.mp3,*.csv
set ruler
set tw=79
set smartindent
set ignorecase
set smartcase
set hlsearch
set incsearch
set lazyredraw
set t_Co=256
set backspace=indent,eol,start
let python_highlight_all=1
let cpp_highlight_all=1
let haskell_highlight_all=1
set showmatch
set t_Co=256
set foldcolumn=2
